server:
  port: 9001

spring:
  application:
    name: DateTime MCP Server
  ai:
    mcp:
      server:
        enabled: true
        name: "DateTime MCP Server"
        version: "1.0.0"
        instructions: "提供本地时间获取、计算等功能的MCP服务器"
        stdio: true
        type: sync
        capabilities:
          tool: true
          completion: false
          prompt: false
          resource: false

logging:
  level:
    com.kun.datemcpserver: DEBUG
    org.springframework.ai.mcp: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

